### ISSUE TITLE
Notifications when a container stops running

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#2324] opened 2024-04-04 20:41 UTC
### Description/Context

We need to be notified if/when a running docker container stops. Currently in cases where we have load balanced instances, if a container fronted by traefik dies, we don't seem to get any alerts/notifications about it.

**Comment by Ardiea** [comment] 2024-04-08 12:17
Relates to https://github.com/mitodl/ol-infrastructure/issues/1426

**Comment by blarghmatey** [comment] 2024-08-08 13:25
Closing as a duplicate of https://github.com/mitodl/ol-infrastructure/issues/1426

**Closed by blarghmatey** 2024-08-08 13:25 UTC
Labels: Monitoring and Alerting, product:infrastructure
