### ISSUE TITLE
Need to know when containers outside the healthcheck path go down

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1426] opened 2023-03-31 16:47 UTC
We don't always know if a docker container that isn't in the 'critical path' has stopped running. For instance, if a traefik or application container crashes, the aws lb will notice that things have stopped responding and it iwll eventuall kill the instance and bring in new ones. BUT, if a celery container crashes, because it isn't part of the healthcheck in any way, the service could end up offline. We need some kind of alert for when this happens. If this ends up being a thing that happens a lot, then we should automate a mitigation and / or find root causes for this troubling behavior.

**Comment by blarghmatey** [comment] 2024-08-26 14:16
Closing as a duplicate of https://github.com/mitodl/ol-infrastructure/issues/1367

**Closed by blarghmatey** 2024-08-26 14:16 UTC
Labels: DevOps, Monitoring and Alerting, product:infrastructure
