### ISSUE TITLE
StarCellBio has moved page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1568] opened 2023-06-09 19:58 UTC
# User Story

As a user, I'd like to know what happened to the site that was at starcellbio.mit.edu 

# Description/Context

We need a brief page that directs users to download the code from github. Something like:

> StarCellBio is no longer being hosted by MIT. 
> 
> The site's source code is available free and open at https://github.com/starteam/starcellbio_html 

# Acceptance Criteria

- [x] respond to requests at https://starcellbio.mit.edu/

# Plan/Design

TBD

**Comment by shaidar** [comment] 2023-06-27 16:17
This looks like a good candidate to use our existing fastly ol-redirect distribution. Only caveat would be that the distro only redirects and doesn't host a static page. Would it be acceptable to update the README file in the GitHub repo to mention that the app is no longer being hosed by MIT? @pdpinch @blarghmatey

**Comment by pdpinch** [comment] 2023-06-27 16:19
Ok. Open a PR and I will review it. 

Will Fastly redirect all URLs on starcellbio.mit.edu to the ReadMe page?

**Comment by shaidar** [comment] 2023-06-27 22:25
This should be all set. Please close this issue once confirmed.

**Closed** 2023-07-05 15:30 UTC
Labels: Infrastructure, product:infrastructure
